spring.application.name=aurora
server.port=1012
spring.datasource.name=aurora
spring.datasource.url=jdbc:mysql://localhost:3306/aurora?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.application.name=app_aurora
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.hibernate=DEBUG
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
debug=true
spring.servlet.multipart.file-size-threshold=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
server.servlet.context-path=/
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:/src/main/resources/img/
# Configuraci\u00f3n de correo electr\u00f3nico


